version: "3.7"
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=r00ts€cr€t
      - MYSQL_DATABASE=ucalendar
    expose:
      - 3306
  api:
    image: ruben/ucalendar-back
    expose:
      - 3000
    environment:
      - DATABASE_URL=mysql://root:r00ts€cr€t@db:3306/ucalendar
  front:
    image: ruben/ucalendar-front
    ports:
      - 80:80
