export const data = {
  degrees: [
    { id: 1714, name: "GRADO EN INGENIERÍA INFORMÁTICA" },
    { id: 1716, name: "GRADO EN INGENIERÍA AEROESPACIAL" },
    {
      id: 1717,
      name:
        "GRADO EN INGENIERÍA EN DISEÑO INDUSTRIAL Y DESARROLLO DEL PRODUCTO",
    },
    { id: 1718, name: "GRADO EN INGENIERÍA ELÉCTRICA" },
    { id: 1719, name: "GRADO EN INGENIERÍA ELECTRÓNICA INDUSTRIAL" },
    { id: 1720, name: "GRADO EN INGENIERÍA MECÁNICA" },
    { id: 1721, name: "GRADO EN INGENIERÍA EN TECNOLOGÍAS INDUSTRIALES" },
    { id: 1725, name: "GRADO EN INGENIERÍA INFORMÁTICA" },
    { id: 1762, name: "MÁSTER EN INGENIERÍA ACÚSTICA" },
    { id: 1763, name: "MÁSTER EN INGENIERÍA DE FABRICACIÓN" },
    {
      id: 1764,
      name:
        "MÁSTER EN INVESTIGACIÓN EN INGENIERÍA DE SISTEMAS Y DE LA COMPUTACIÓN",
    },
    {
      id: 1765,
      name:
        "MÁSTER EN INVESTIGACIÓN EN INGENIERÍA DE SISTEMAS Y DE LA COMPUTACIÓN",
    },
    { id: 1766, name: "MÁSTER EN PREVENCIÓN DE RIESGOS LABORALES" },
    { id: 1768, name: "MÁSTER EN INGENIERÍA INDUSTRIAL" },
    { id: 1769, name: "MÁSTER EN SEGURIDAD INFORMÁTICA (CIBERSEGURIDAD)" },
  ],
  subjects: [
    {
      degreeId: 1725,
      abrev: "OGE",
      id: 21714001,
      name: "ORGANIZACIÓN Y GESTIÓN DE EMPRESAS",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "EST",
      id: 21714002,
      name: "ESTADÍSTICA",
      semester: false,
    },
    {
      degreeId: 1725,
      abrev: "FFE",
      id: 21714003,
      name: "FUNDAMENTOS FÍSICOS Y ELECTRÓNICOS DE LA INFORMÁTICA",
      semester: false,
    },
    {
      degreeId: 1725,
      abrev: "FEC",
      id: 21714004,
      name: "FUNDAMENTOS DE ESTRUCTURA DE COMPUTADORES",
      semester: false,
    },
    {
      degreeId: 1725,
      abrev: "IG",
      id: 21714005,
      name: "INFORMÁTICA GENERAL",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "IP",
      id: 21714006,
      name: "INTRODUCCIÓN A LA PROGRAMACIÓN",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "MP",
      id: 21714007,
      name: "METODOLOGÍA DE LA PROGRAMACIÓN",
      semester: false,
    },
    {
      degreeId: 1725,
      abrev: "ALG",
      id: 21714008,
      name: "ÁLGEBRA",
      semester: false,
    },
    {
      degreeId: 1725,
      abrev: "CAL",
      id: 21714009,
      name: "CÁLCULO",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "MD",
      id: 21714010,
      name: "MATEMÁTICA DISCRETA",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "BD",
      id: 21714011,
      name: "BASES DE DATOS",
      semester: false,
    },
    {
      degreeId: 1725,
      abrev: "IS",
      id: 21714012,
      name: "INGENIERÍA DEL SOFTWARE",
      semester: false,
    },
    {
      degreeId: 1725,
      abrev: "IA",
      id: 21714013,
      name: "INTELIGENCIA ARTIFICIAL",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "AAED",
      id: 21714014,
      name: "ANÁLISIS DE ALGORITMOS Y ESTRUCTURAS DE DATOS",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "DA",
      id: 21714015,
      name: "DISEÑO DE ALGORITMOS",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "EDNL",
      id: 21714016,
      name: "ESTRUCTURAS DE DATOS NO LINEALES",
      semester: false,
    },
    {
      degreeId: 1725,
      abrev: "POO",
      id: 21714017,
      name: "PROGRAMACIÓN ORIENTADA A OBJETOS",
      semester: false,
    },
    {
      degreeId: 1725,
      abrev: "PINF",
      id: 21714018,
      name: "PROYECTOS INFORMÁTICOS",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "AC",
      id: 21714019,
      name: "ARQUITECTURA DE COMPUTADORES",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "PCTR",
      id: 21714020,
      name: "PROGRAMACIÓN CONCURRENTE Y DE TIEMPO REAL",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "RC",
      id: 21714021,
      name: "REDES DE COMPUTADORES",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "SD",
      id: 21714022,
      name: "SISTEMAS DISTRIBUIDOS",
      semester: false,
    },
    {
      degreeId: 1725,
      abrev: "SO",
      id: 21714023,
      name: "SISTEMAS OPERATIVOS",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "CC",
      id: 21714024,
      name: "COMPLEJIDAD COMPUTACIONAL",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "MC",
      id: 21714025,
      name: "MODELOS DE COMPUTACIÓN",
      semester: false,
    },
    {
      degreeId: 1725,
      abrev: "PL",
      id: 21714026,
      name: "PROCESADORES DE LENGUAJES",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "TALF",
      id: 21714027,
      name: "TEORÍA DE AUTÓMATAS Y LENGUAJES FORMALES",
      semester: false,
    },
    {
      degreeId: 1725,
      abrev: "APC",
      id: 21714028,
      name: "APRENDIZAJE COMPUTACIONAL",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "P",
      id: 21714029,
      name: "PERCEPCIÓN",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "RP",
      id: 21714030,
      name: "RECONOCIMIENTO DE PATRONES",
      semester: false,
    },
    {
      degreeId: 1725,
      abrev: "SI",
      id: 21714031,
      name: "SISTEMAS INTELIGENTES",
      semester: false,
    },
    {
      degreeId: 1725,
      abrev: "ACPD",
      id: 21714032,
      name: "ARQUITECTURAS DE COMPUTADORES PARALELOS Y DISTRIBUIDOS",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "PPD",
      id: 21714033,
      name: "PROGRAMACIÓN PARALELA Y DISTRIBUIDA",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "DAAC",
      id: 21714034,
      name: "DISEÑO AVANZADO DE ARQUITECTURA DE COMPUTADORES",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "DBM",
      id: 21714035,
      name: "DISEÑO BASADO EN MICROPROCESADORES",
      semester: false,
    },
    {
      degreeId: 1725,
      abrev: "DCE",
      id: 21714036,
      name: "DISEÑO DE COMPUTADORES EMPOTRADOS",
      semester: false,
    },
    {
      degreeId: 1725,
      abrev: "TDC",
      id: 21714037,
      name: "TÉCNICAS DE DISEÑO DE COMPUTADORES",
      semester: false,
    },
    {
      degreeId: 1725,
      abrev: "ASRC",
      id: 21714038,
      name: "ADMINISTRACIÓN Y SEGURIDAD DE REDES DE COMPUTADORES",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "DRC",
      id: 21714039,
      name: "DISEÑO DE REDES DE COMPUTADORES",
      semester: false,
    },
    {
      degreeId: 1725,
      abrev: "DSS",
      id: 21714040,
      name: "DISEÑO DE SISTEMAS SOFTWARE",
      semester: false,
    },
    {
      degreeId: 1725,
      abrev: "IR",
      id: 21714041,
      name: "INGENIERÍA DE REQUISITOS",
      semester: false,
    },
    {
      degreeId: 1725,
      abrev: "VVS",
      id: 21714042,
      name: "VERIFICACIÓN Y VALIDACIÓN DEL SOFTWARE",
      semester: false,
    },
    {
      degreeId: 1725,
      abrev: "CS",
      id: 21714043,
      name: "CALIDAD DEL SOFTWARE",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "DGPS",
      id: 21714044,
      name: "DIRECCIÓN Y GESTIÓN DE PROYECTOS SOFTWARE",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "MPS",
      id: 21714045,
      name: "METODOLOGÍAS Y PROCESOS SOFTWARE",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "ES",
      id: 21714046,
      name: "EVOLUCIÓN DEL SOFTWARE",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "IISS",
      id: 21714047,
      name: "IMPLEMENTACIÓN E IMPLANTACIÓN DE SISTEMAS SOFTWARE",
      semester: false,
    },
    {
      degreeId: 1725,
      abrev: "DSH",
      id: 21714048,
      name: "DESARROLLO DE SISTEMAS HIPERMEDIA",
      semester: false,
    },
    {
      degreeId: 1725,
      abrev: "PNET",
      id: 21714049,
      name: "PROGRAMACIÓN EN INTERNET",
      semester: false,
    },
    {
      degreeId: 1725,
      abrev: "REC",
      id: 21714050,
      name: "RECUPERACIÓN DE LA INFORMACIÓN",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "ISI",
      id: 21714051,
      name: "INGENIERÍA DE SISTEMAS DE INFORMACIÓN",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "SIE",
      id: 21714052,
      name: "SISTEMAS DE INFORMACIÓN EN LA EMPRESA",
      semester: false,
    },
    {
      degreeId: 1725,
      abrev: "ABD",
      id: 21714053,
      name: "ADMINISTRACIÓN DE BASES DE DATOS",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "TABD",
      id: 21714054,
      name: "TECNOLOGÍAS AVANZADAS DE BASES DE DATOS",
      semester: false,
    },
    {
      degreeId: 1725,
      abrev: "TIN",
      id: 21714055,
      name: "TECNOLOGÍAS DE INTELIGENCIA DE NEGOCIO",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "AS",
      id: 21714056,
      name: "ADMINISTRACIÓN DE SERVIDORES",
      semester: false,
    },
    {
      degreeId: 1725,
      abrev: "ICR",
      id: 21714057,
      name: "INTERCONEXIÓN DE REDES",
      semester: false,
    },
    {
      degreeId: 1725,
      abrev: "CSI",
      id: 21714058,
      name: "CALIDAD DE LOS SISTEMAS INFORMÁTICOS",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "SSI",
      id: 21714059,
      name: "SEGURIDAD EN LOS SISTEMAS INFORMÁTICOS",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "IW",
      id: 21714061,
      name: "INGENIERÍA WEB",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "INE",
      id: 21714062,
      name: "INTERNET Y NEGOCIO ELECTRÓNICO",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "PW",
      id: 21714063,
      name: "PROGRAMACIÓN WEB",
      semester: false,
    },
    {
      degreeId: 1725,
      abrev: "TFG",
      id: 21714064,
      name: "PROYECTO FIN DE GRADO",
      semester: false,
    },
    {
      degreeId: 1725,
      abrev: "IPO",
      id: 21714080,
      name: "INTERACCIÓN PERSONA-ORDENADOR",
      semester: false,
    },
    {
      degreeId: 1725,
      abrev: "PC",
      id: 21714083,
      name: "PRÁCTICAS CURRICULARES",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "SDIG",
      id: 21714084,
      name: "SISTEMAS DIGITALES",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "VS",
      id: 21714085,
      name: "VIRTUALIZACIÓN DE SISTEMAS",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "EA",
      id: 21719026,
      name: "ELECTRÓNICA ANALÓGICA",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "IE",
      id: 21719029,
      name: "INSTRUMENTACIÓN ELECTRÓNICA",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "RA",
      id: 21719030,
      name: "REGULACIÓN AUTOMÁTICA",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "AI",
      id: 21719031,
      name: "AUTOMATIZACIÓN INDUSTRIAL",
      semester: true,
    },
    {
      degreeId: 1725,
      abrev: "DDPE",
      id: 21719034,
      name: "DISEÑO Y DESARROLLO DE PROTOTIPOS ELECTRÓNICOS",
      semester: true,
    },
  ],
};
